# NumPy
A python library for performing numerical computation.

In [1]:
import numpy as np # Numerical Computation

## How to instantiate NumPy arrays

### Using `np.array`

In [17]:
arr = np.array([1, 2, 6, 8]) # array-like object is passed
print(arr, type(arr))

[1 2 6 8] <class 'numpy.ndarray'>


### Using user-friendly APIs provided by `numpy`
- `np.arange`
- `np.linspace`
- `np.random.random`

In [79]:
arr1 = np.arange(1, 10, 2)
print(arr1)
arr2 = np.arange(10) # 0 to 10(excluded)
print(arr2)

[1 3 5 7 9]
[0 1 2 3 4 5 6 7 8 9]


In [80]:
t = np.linspace(10, 10.2, 10)
print(t)

[10.         10.02222222 10.04444444 10.06666667 10.08888889 10.11111111
 10.13333333 10.15555556 10.17777778 10.2       ]


In [87]:
arr = np.random.random(10)
print(arr)
print(arr.shape, arr.ndim)

[0.46414008 0.90148875 0.01848855 0.58663472 0.32002122 0.36823626
 0.53662756 0.13304774 0.41019008 0.06316759]
(10,) 1


## Properties of a numpy array
- shape: Tells about the shape of the array.
- ndim: Tells about the dimension of the array.

In [81]:
arr = np.array([[1, 2, 3]])

Scalar: 1 ... \
Collection of scalars: 1D array \
Collection of 1D array: 2D array

In [82]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a)
print(a.shape)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [83]:
a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [84]:
print(a.shape)
print(a.ndim)

(2, 2, 3)
3


## Extracting elements from array

In [94]:
arr = np.array([5, 4, 3, 2, 1])
print(arr)
print("-----")
print(arr[:-1])

[5 4 3 2 1]
[5 4 3 2]


In [120]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) # image => 
print(arr)
print("----")
print(arr[1, 1, 0])

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
----
4
