<div style="font-family: 'Georgia', serif; border-left: 3px solid #ccc; padding-left: 12px; margin-bottom: 1em;">
  <h2 style="margin: 0; color: #EF8C00; font-size: 2.4em; padding-left: 0; text-indent: 0;">
      Numpy
  </h2>
    <p>
        array, type, ndim, shape, size
    </p>
</div>

In [2]:
import numpy as np

## Array

In [5]:
arr = np.array([1, 2, 3])

### type
The type of any numpy array will be `np.ndarray`

In [7]:
type(arr)

numpy.ndarray

### ndim
Every `np.ndarray` object has `ndim` attribute that returns `int`.

In [24]:
arr = np.array(1) # 0 => Scalar => A number (no datastructure)
print(f"arr={arr}, \tndim={arr.ndim}\n")

arr = np.array([]) # 1 => Collection of scalar (0D array)
print(f"arr={arr}, ndim={arr.ndim}\n")

arr = np.array([1, 2, 3]) # 1 => Collection of scalar (0D array) => Also known as vector
print(f"arr={arr}, ndim={arr.ndim}\n")

arr = np.array([[], []]) # 2 => Collection of vector (1D array) => Also known as matrix
print(f"arr={arr}, ndim={arr.ndim}\n")

arr = np.array([[1, 2, 3], [5, 6, 7]]) # 2 => Collection of vector (1D array) => Also known as matrix
print(f"arr={arr}, ndim={arr.ndim}\n")

arr = np.array([[1, 2, 3]]) # 2 => Collection of vector (1D array) => Also known as matrix
print(f"arr={arr}, ndim={arr.ndim}\n")

arr = np.array([[[1, 2, 3]]]) # 3 => Collection of matrix (2D array) => Also known as 3D
print(f"arr={arr}, ndim={arr.ndim}\n")

arr=1, 	ndim=0

arr=[], ndim=1

arr=[1 2 3], ndim=1

arr=[], ndim=2

arr=[[1 2 3]
 [5 6 7]], ndim=2

arr=[[1 2 3]], ndim=2

arr=[[[1 2 3]]], ndim=3



### shape
Every `np.ndarray` object has `shape` attribute that returns `tuple` of length `ndim`.

In [61]:
arr = np.array(1) # 0 => Scalar => A number (no datastructure)
print(f"arr={arr}, \tndim={arr.ndim}, shape={arr.shape}\n")

arr = np.array([]) # 1 => Collection of scalar (0D array)
print(f"arr={arr}, ndim={arr.ndim}, shape={arr.shape}\n")

arr = np.array([1, 2, 3]) # 1 => Collection of scalar (0D array) => Also known as vector
print(f"arr={arr}, ndim={arr.ndim}, shape={arr.shape}\n")

arr = np.array([[], []]) # 2 => Collection of vector (1D array) => Also known as matrix
print(f"arr={arr}, ndim={arr.ndim}, shape={arr.shape}\n")

arr = np.array([[1, 2, 3], [5, 6, 7]]) # 2 => Collection of vector (1D array) => Also known as matrix
print(f"arr={arr}, ndim={arr.ndim}, shape={arr.shape}\n")

arr = np.array([[1, 2, 3]]) # 2 => Collection of vector (1D array) => Also known as matrix (row vector)
print(f"arr={arr}, ndim={arr.ndim}, shape={arr.shape}\n")

arr = np.array([[1], [2], [3]]) # 2 => Collection of vector (1D array) => Also known as matrix (column vector)
print(f"arr={arr}, ndim={arr.ndim}, shape={arr.shape}\n")

arr = np.array([[[1, 2, 3]]]) # 3 => Collection of matrix (2D array) => Also known as 3D
print(f"arr={arr}, ndim={arr.ndim}, shape={arr.shape}\n")

arr=1, 	ndim=0, shape=()

arr=[], ndim=1, shape=(0,)

arr=[1 2 3], ndim=1, shape=(3,)

arr=[], ndim=2, shape=(2, 0)

arr=[[1 2 3]
 [5 6 7]], ndim=2, shape=(2, 3)

arr=[[1 2 3]], ndim=2, shape=(1, 3)

arr=[[1]
 [2]
 [3]], ndim=2, shape=(3, 1)

arr=[[[1 2 3]]], ndim=3, shape=(1, 1, 3)



### size
Every `np.ndarray` object has `size` attribute that returns `int`. It is basically the total number of scalar objects.

In [66]:
arr = np.array(1) # 0 => Scalar => A number (no datastructure)
print(f"arr={arr}, \tndim={arr.ndim}, shape={arr.shape} size={arr.size}\n")

arr = np.array([]) # 1 => Collection of scalar (0D array)
print(f"arr={arr}, ndim={arr.ndim}, shape={arr.shape} size={arr.size}\n")

arr = np.array([1, 2, 3]) # 1 => Collection of scalar (0D array) => Also known as vector
print(f"arr={arr}, ndim={arr.ndim}, shape={arr.shape} size={arr.size}\n")

arr = np.array([[], []]) # 2 => Collection of vector (1D array) => Also known as matrix
print(f"arr={arr}, ndim={arr.ndim}, shape={arr.shape} size={arr.size}\n")

arr = np.array([[1, 2, 3], [5, 6, 7]]) # 2 => Collection of vector (1D array) => Also known as matrix
print(f"arr={arr}, ndim={arr.ndim}, shape={arr.shape} size={arr.size}\n")

arr = np.array([[1, 2, 3]]) # 2 => Collection of vector (1D array) => Also known as matrix (row vector)
print(f"arr={arr}, ndim={arr.ndim}, shape={arr.shape} size={arr.size}\n")

arr = np.array([[1], [2], [3]]) # 2 => Collection of vector (1D array) => Also known as matrix (column vector)
print(f"arr={arr}, ndim={arr.ndim}, shape={arr.shape} size={arr.size}\n")

arr = np.array([[[1, 2, 3]]]) # 3 => Collection of matrix (2D array) => Also known as 3D
print(f"arr={arr}, ndim={arr.ndim}, shape={arr.shape} size={arr.size}\n")

arr=1, 	ndim=0, shape=() size=1

arr=[], ndim=1, shape=(0,) size=0

arr=[1 2 3], ndim=1, shape=(3,) size=3

arr=[], ndim=2, shape=(2, 0) size=0

arr=[[1 2 3]
 [5 6 7]], ndim=2, shape=(2, 3) size=6

arr=[[1 2 3]], ndim=2, shape=(1, 3) size=3

arr=[[1]
 [2]
 [3]], ndim=2, shape=(3, 1) size=3

arr=[[[1 2 3]]], ndim=3, shape=(1, 1, 3) size=3

